# Generated by Django 3.2.6 on 2022-02-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coinId',
            field=models.CharField(max_length=16),
        ),
    ]
