# Generated by Django 3.2.6 on 2022-02-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_coin_coinid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='currentPrice',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name='coin',
            name='high24h',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name='coin',
            name='low24h',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
        migrations.AlterField(
            model_name='coin',
            name='priceChangePercentage24h',
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
    ]
