# Generated by Django 3.2.6 on 2022-02-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220208_1817'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='coin',
            order_with_respect_to='marketCapRank',
        ),
    ]
