# Generated by Django 3.2.6 on 2022-02-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_coin_order_with_respect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
